services:
  postgres:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/balneario-project
    container_name: backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/appdb
    ports:
      - "3000:3000"
    volumes:
      - ./backend/balneario-project:/app
    working_dir: /app
    entrypoint: ["/app/entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3001:3000" # Mapea el 3000 del contenedor al 3001 del host
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    working_dir: /app
    command: npm run dev

volumes:
  postgres_data:
